import type { TradeType, TradeCustomizationConfig, ModuleFlags } from '@/types/trade'

export const DEFAULT_MODULE_FLAGS: ModuleFlags = {
  dashboard: true,
  clients: true,
  projects: true,
  schedule: true,
  purchaseOrders: true,
  vanStock: true,
  fleet: true,
  safety: true,
  timesheets: true,
  financials: true,
  files: true,
}

export interface TradePresetInfo {
  id: TradeType
  title: string
  subtitle: string
  icon: string
  color: string
  badgeColor: string
  config: TradeCustomizationConfig
}

export const TRADE_PRESETS: Record<TradeType, TradePresetInfo> = {
  electrical: {
    id: 'electrical',
    title: 'Electrical & Automation',
    subtitle: 'Commercial & Domestic Electrical, HVAC & Data',
    icon: 'electric_bolt',
    color: 'from-amber-500/20 to-yellow-500/10 border-amber-500/30 text-amber-400',
    badgeColor: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    config: {
      tradeType: 'electrical',
      tradeName: 'Electrical & Automation',
      description: 'Optimized for electrical contractors, test verification, switchboards, and site compliance.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Project',
        projects: 'Projects',
        task: 'Work Order',
        tasks: 'Work Orders',
        costCenter: 'Cost Center',
        costCenters: 'Cost Centers',
        technician: 'Technician',
        technicians: 'Technicians',
        clients: 'Clients',
        vanStock: 'Van Stock & Materials',
        fleet: 'Fleet & Vehicles',
        safety: 'Safety & Permits',
        timesheets: 'Timesheets',
        purchaseOrders: 'Purchase Orders',
        financials: 'Financials & Margins',
        schedule: 'Schedule & Dispatch',
        files: 'Files Hub',
      },
    },
  },

  plumbing: {
    id: 'plumbing',
    title: 'Plumbing, Gas & Drainage',
    subtitle: 'Residential & Commercial Plumbing, Gasfitting, Roofing',
    icon: 'plumbing',
    color: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400',
    badgeColor: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
    config: {
      tradeType: 'plumbing',
      tradeName: 'Plumbing, Gas & Drainage',
      description: 'Tailored for plumbing contractors, gas test logs, backflow valves, and drainage jobs.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Job',
        projects: 'Jobs & Sites',
        task: 'Maintenance Task',
        tasks: 'Maintenance Tasks',
        costCenter: 'Cost Center',
        costCenters: 'Cost Centers',
        technician: 'Plumber / Gasfitter',
        technicians: 'Plumbers & Crew',
        clients: 'Clients & Owners',
        vanStock: 'Fittings & Consumables',
        fleet: 'Service Vans & Rigs',
        safety: 'Safety & Gas Certs',
        timesheets: 'Timesheets',
        purchaseOrders: 'Merchant POs',
        financials: 'Financials',
        schedule: 'Job Dispatch & Calendar',
        files: 'Site Plans & Gas Logs',
      },
    },
  },

  automotive: {
    id: 'automotive',
    title: 'Automotive & Heavy Diesel',
    subtitle: 'Mobile Mechanics, Fleet Workshops & Diesel Repairs',
    icon: 'car_repair',
    color: 'from-red-500/20 to-orange-500/10 border-red-500/30 text-red-400',
    badgeColor: 'bg-red-500/20 text-red-400 border-red-500/30',
    config: {
      tradeType: 'automotive',
      tradeName: 'Automotive & Heavy Diesel',
      description: 'Engineered for workshops, repair orders, VIN vehicle tracking, and parts inventory.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Job Card',
        projects: 'Job Cards',
        task: 'Repair Line',
        tasks: 'Repair Lines',
        costCenter: 'Labor / Parts Code',
        costCenters: 'Labor & Parts Codes',
        technician: 'Mechanic',
        technicians: 'Mechanics & Techs',
        clients: 'Fleet Customers',
        vanStock: 'Parts & Lubricants',
        fleet: 'Fleet Assets & VINs',
        safety: 'Pre-Start & Hot Work',
        timesheets: 'Clocked Labor Hours',
        purchaseOrders: 'Parts Orders',
        financials: 'Job Card Billing',
        schedule: 'Workshop Bay Booking',
        files: 'Diagnostics & Schematics',
      },
    },
  },

  civil: {
    id: 'civil',
    title: 'Civil & Earthmoving',
    subtitle: 'Excavation, Roading, Civil Contracting & Plant Hire',
    icon: 'construction',
    color: 'from-amber-600/20 to-orange-600/10 border-amber-600/30 text-amber-500',
    badgeColor: 'bg-amber-600/20 text-amber-500 border-amber-600/30',
    config: {
      tradeType: 'civil',
      tradeName: 'Civil & Earthmoving',
      description: 'Designed for civil sites, heavy plant operators, aggregate materials, and daily run sheets.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Site',
        projects: 'Civil Sites',
        task: 'Scope Item',
        tasks: 'Scope Items',
        costCenter: 'Cost Code',
        costCenters: 'Cost Codes',
        technician: 'Machine Operator',
        technicians: 'Operators & Drivers',
        clients: 'Principals & Tier 1s',
        vanStock: 'Aggregate & Consumables',
        fleet: 'Heavy Plant & Machinery',
        safety: 'Site JSA & Pre-Starts',
        timesheets: 'Daily Run Sheets',
        purchaseOrders: 'Quarry & Material POs',
        financials: 'Contract Claims & Budgets',
        schedule: 'Plant & Site Allocation',
        files: 'Engineering Drawings & GPS',
      },
    },
  },

  landscaping: {
    id: 'landscaping',
    title: 'Landscaping & Exterior Wash',
    subtitle: 'Grounds Maintenance, Pressure Washing & Exterior Cleaning',
    icon: 'yard',
    color: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/30 text-emerald-400',
    badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    config: {
      tradeType: 'landscaping',
      tradeName: 'Landscaping & Exterior Wash',
      description: 'Ideal for grounds care, pressure wash rigs, service run routes, and recurring property maintenance.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Property',
        projects: 'Properties & Contracts',
        task: 'Service Run',
        tasks: 'Service Runs',
        costCenter: 'Service Type',
        costCenters: 'Service Types',
        technician: 'Crew Member',
        technicians: 'Crew & Team Leads',
        clients: 'Property Owners & Managers',
        vanStock: 'Chemicals & Rig Supplies',
        fleet: 'Trucks, Mowers & Rigs',
        safety: 'Safety & Chemical Safety',
        timesheets: 'Crew Hours',
        purchaseOrders: 'Supplier Orders',
        financials: 'Job Margins',
        schedule: 'Route & Run Dispatch',
        files: 'Site Maps & Before/Afters',
      },
    },
  },

  custom: {
    id: 'custom',
    title: 'Custom / General Trade',
    subtitle: 'Bespoke trade configuration with custom terms & module switches',
    icon: 'tune',
    color: 'from-purple-500/20 to-indigo-500/10 border-purple-500/30 text-purple-400',
    badgeColor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    config: {
      tradeType: 'custom',
      tradeName: 'General Field Operations',
      description: 'Full manual control over terminology aliases and module visibility.',
      modules: { ...DEFAULT_MODULE_FLAGS },
      terminology: {
        project: 'Project',
        projects: 'Projects',
        task: 'Task',
        tasks: 'Tasks',
        costCenter: 'Cost Center',
        costCenters: 'Cost Centers',
        technician: 'Team Member',
        technicians: 'Team Members',
        clients: 'Clients',
        vanStock: 'Materials & Stock',
        fleet: 'Vehicles & Equipment',
        safety: 'Safety Compliance',
        timesheets: 'Timesheets',
        purchaseOrders: 'Purchase Orders',
        financials: 'Financials',
        schedule: 'Schedule & Calendar',
        files: 'Document Hub',
      },
    },
  },
}
